### ISSUE TITLE
Assistance Needed with Mule Chain Project Installation Error

### ISSUE THREAD

**Issue by umamaheshm** [MuleSoft-AI-Chain-Project/example-mule-apps#1]
Hi ,

I hope you’re well. I am writing to inform you that I am encountering the same error with Mule Chain Project installation on my laptop again. Despite following the troubleshooting steps we discussed previously, the issue persists.

**Your suggestion:**  can you please use mvn clean install -DskipMunitTests. Just saw it, we will add it to the docs. Also make sure to compile with Java 8. 

I followed your suggestion... But again i'm facing same error message.. I've attached the screen shots about the error i faced.. for detail observation..

Could you please provide further guidance or suggest any additional steps to resolve this issue? If there are any specific logs or additional information required, I am happy to provide them.

Thank you for your assistance.

Best regards,
umamahesh.M
![test1](https://github.com/MuleChain-Project/example-mule-apps/assets/27778656/b3c08cee-df1d-487a-97e9-4a52e7f56d06)
![test2](https://github.com/MuleChain-Project/example-mule-apps/assets/27778656/1bebed6b-d822-474e-8b5a-a8521772a1a1)
![test3](https://github.com/MuleChain-Project/example-mule-apps/assets/27778656/d1d4c6e9-d4e6-41ec-870f-8d81c53fabbe)
![test4](https://github.com/MuleChain-Project/example-mule-apps/assets/27778656/4d91cfcf-12f6-4d35-acd2-bbef31189ad6)

**Comment by amirkhan-ak-sf** [comment]
I believe this has been fixed by running the command `mvn clean install -Dmaven.test.skip=true -DskipTests`
